# fly.toml app configuration file generated for happytown on 2026-02-06T16:38:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "happytown"
primary_region = "iad"
console_command = "./bin/rails console"

[deploy]
  strategy = "bluegreen"
  release_command = "./bin/rails db:prepare"

[env]
  RAILS_LOG_LEVEL = "debug"
  HTTP_PORT = "8080"
  HTTPS_PORT = "8443"
  CANONICAL_HOST = "happytown.life"

[processes]
  # app = "./bin/thrust ./bin/rails server"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "15s"
  method = "GET"
  path = "/up"
  protocol = "http"
  # tls_skip_verify = false

  # [http_service.checks.headers]
  #   X-Forwarded-Proto = "https"

[[vm]]
  memory = "1gb"
  cpus = 1
  memory_mb = 1024
