open_router: &open_router
  service: OpenRouter
  access_token: <%= Rails.application.credentials.dig(:open_router, :api_key) %>
  model: openrouter/aurora-alpha

development:
  open_router: *open_router

production:
  open_router: *open_router
