open_router: &open_router
  service: OpenRouter
  access_token: <%= Rails.application.credentials.dig(:open_router, :api_key) %>
  model: stepfun/step-3.5-flash:free

development:
  open_router: *open_router

production:
  open_router: *open_router
