# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  truncate_webhook_messages:
    class: TruncateWebhookMessagesJob
    schedule: at 4am America/Toronto every day
  clear_solid_queue_finished_jobs:
    command:
      "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  reconcile_whatsapp_group_metadata:
    class: ReconcileWhatsappGroupMetadataJob
    schedule: at 5am America/Toronto every day
